# wait
model: 'custom'
model_dir: 'data/model_lf_s1_s2'
network: 'res'
heads: ''
task: 'pvnet'
gpus: (0, 1, 2, 3)
resume: true        # if we want to continue training from last saved model

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 300
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.5
    batch_size: 4
    dataset: 'CustomComplex'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    batch_sampler: 'image_size'
    stokes_params: ["_dolp.jpg", "_aolp.jpg"]
    pol_inference: False
test:
    dataset: 'CustomTest'
    batch_size: 1
    batch_sampler: 'image_size'
